language: python
python:
  - "2.7"
  - "3.4"
install:
    - pip install -r requirements.txt
    - pip install braintree coveralls mock mysqlclient
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgres
addons:
  postgresql: "9.4"
  code_climate:
        repo_token: 7a232fcf4e6798719ca6e8ff360a106ce48e04cb2727442f46e23aa166bb3a6a
script:
  - coverage run --source=hc manage.py test
after_success: coveralls
cache: pip
