# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_check_nag_after'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check',
            name='nag_after',
        ),
    ]
