# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-10 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_check_nag_after'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='nag_set',
            field=models.BooleanField(default=True),
        ),
    ]
